version: 0.2

phases:
  pre_build:
    commands:
      - echo Experimental Feature
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - echo Logging in to Amazon ECR...
      - aws --version
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - IMAGE_NAME=multi-architecture-hello
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image manifest
      - docker manifest create ${REPOSITORY_URI}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}-x86_64 ${REPOSITORY_URI}:${IMAGE_TAG}-aarch64
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images manifest
      - docker manifest push ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo Writing image definitions file...
      - printf '[{"name":"multi-architecture-hello","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
