version: 0.2

phases:
  install:
    commands:
      - ARCH=$(uname -m)
      - echo CPU Architecture $ARCH
      - pip3 uninstall -y awscli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-$ARCH.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - IMAGE_NAME=multi-architecture-hello
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}-$(uname -m)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd app/
      - docker build -t $REPOSITORY_URI:latest-$(uname -m) .
      - docker tag $REPOSITORY_URI:latest-$(uname -m) $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest-$(uname -m)
      - docker push $REPOSITORY_URI:$IMAGE_TAG
